### ISSUE TITLE
arm64 安装成功后aria2正常工作，但是filemanager 一直打不开

### ISSUE THREAD

**Issue by fanyh123** [wahyd4/aria2-ariang-docker#17] opened 2019-02-20 14:15 UTC
![image](https://user-images.githubusercontent.com/15026816/53097428-63d9eb00-355c-11e9-9ed2-1b2864241433.png)
浏览器开发者模式看到当打开 http://ip/files 时所需静态文件不存在。都是404。并且容器中/usr/local/www/aria2/ 文件下确实没有static文件夹。多次重新部署还是不行。
![image](https://user-images.githubusercontent.com/15026816/53097678-0003f200-355d-11e9-8d24-b61fefd06491.png)

**Comment by wahyd4** [comment] 2019-02-20 20:45
This issue was caused by #15 , and now just have been fixed by replacing with the previous image.
Please pull the latest docker image `docker pull wahyd4/aria2-ui:arm64` and then try it again.

Cheers

**Closed by wahyd4** 2019-02-20 20:45 UTC

**Comment by fanyh123** [comment] 2019-02-21 03:57
重新执行`docker pull wahyd4/aria2-ui:arm64 `，解决了。非常感谢

**Comment by fanyh123** [comment] 2019-02-21 04:06
FilesManager管理目录可以单独设置吗？希望FilesManager管理根目录目录aria2下载目录不同，怎么设置可以做到？谢谢

**Comment by wahyd4** [comment] 2019-02-21 04:08
Can you open a new issue? cause this a different question.
If you can try to write it in English, that would be awesome.
