### ISSUE TITLE
Problem in mounting filebrowser.db under Synology Docker

### ISSUE THREAD

**Issue by earthruby** [wahyd4/aria2-ariang-docker#157] opened 2021-04-08 02:09 UTC
I have an issue while mounting filebrowser.db.

My docker image never works if i mount /app/filebrowser.db (Given that i have already created a blank filebrowser.db under docker/Aria2/Conf/)
![image](https://user-images.githubusercontent.com/62000365/113957844-9b967080-9852-11eb-9bcc-833b49551aca.png)

not sure if anyone is facing the same problem as i do...

i run this docker image under Synology NAS Docker, it keeps restarting and shows Docker container: Aria2-UI stopped unexpectedly. (No detail error message under Docker log)

however, if i remove /app/filebrowser.db from volume, this image works normally.

i wonder if the mounting should go under environment under Synology Docker instead

![image](https://user-images.githubusercontent.com/62000365/113958314-70605100-9853-11eb-95db-eb6bc6a28297.png)

any idea on how to solve this?

thanks!

**Comment by wahyd4** [comment] 2021-04-08 03:34
Hi @earthruby , I reproduced the issue you have then I specify a relative path for `filebrowser.db`, the app complains about `open /app/filebrowser.db: is a directory`, but after specifying an absolute file path, it works perfectly.

![WX20210408-133057](https://user-images.githubusercontent.com/836576/113964489-f211a800-986e-11eb-90c5-d36ce61eaf90.png)

So the working command I have with an empty `filebrowser.db` file is:

```
docker run -it --rm  --name aria2-ui -p 8080:80 -v /Users/junv/test/a.db:/app/filebrowser.db  wahyd4/aria2-ui
```
The file name of the `db file` on the host doesn't matter at all.

**Comment by earthruby** [comment] 2021-04-08 03:46
Hi @wahyd4 

Actually i have added the absolute path as a "file" instead of "folder", you can see from the below screen cap, there is an "Add File" option, which i used to mount the filebrowser.db.... (data and conf are mount by Add Folder)

![image](https://user-images.githubusercontent.com/62000365/113957844-9b967080-9852-11eb-9bcc-833b49551aca.png)

in this way, this container cannot start and it keeps restarting and shows Docker container: Aria2-UI stopped unexpectedly. (No detail error message under Docker log)

however, if I add it with "Add Folder" option, it shows exactly the error as yours which says I am trying to mount a directory onto a file....

**Comment by wahyd4** [comment] 2021-04-08 04:05
How do you know you have provided a file with an absolute path instead of a relative path? It looks like a relative path file been provided from your screenshot. 

Have you had any successful experiences `mounting files(not folders)` on Synology? Maybe search a bit about how to mount a file to a docker container on Synology?

In the problematic case I shared, I was actually using the same file. when I mount the file with a relative path, it failed, but when I mount it with an absolute path, it succeeded. I guess that could be related to how Docker volume works in terms of file and folders.

**Comment by earthruby** [comment] 2021-04-08 06:07
i thought the Add File option works as mounting absolute path........
not sure how to mount files in other way, let me dig into it........
thanks for pointing this out~

**Comment by wahyd4** [comment] 2021-08-30 23:54
Hi @earthruby I will close it now due to no further feedback is provided

**Closed by wahyd4** 2021-08-30 23:54 UTC
