### ISSUE TITLE
群晖安装了web端无法打开

### ISSUE THREAD

**Issue by Lasx** [wahyd4/aria2-ariang-docker#131] opened 2020-12-20 07:42 UTC
默认80 443 无法使用，修改了端口浏览器打开页面空白

**Comment by wahyd4** [comment] 2020-12-20 11:56
Please paste the full command you used to run the container.

**Comment by wahyd4** [comment] 2021-01-02 06:30
Hi @Lasx, I will close it now due to no further feedback has been provided. 
But feel free to create a new one with more details.

**Closed by wahyd4** 2021-01-02 06:30 UTC

**Comment by wahyd4** [comment] 2021-01-07 05:31
Hi @Lasx if the issue you experienced was caused by failed to download Rclone UI from Github, please try to pull the latest version docker image and set environment variable `ENABLE_RCLONE` to `false` to disable Rclone, then your container should work.
